# Generated by Django 5.1.6 on 2025-04-26 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_payment_options_remove_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directmessage',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
