# Generated by Django 5.1.6 on 2025-04-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_sent_at_directmessage_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directmessage',
            old_name='created_at',
            new_name='sent_at',
        ),
    ]
