# Generated by Django 5.1.6 on 2025-04-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_directmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directmessage',
            old_name='created_at',
            new_name='sent_at',
        ),
    ]
